### ISSUE TITLE
Inference.json is missing

### ISSUE THREAD

**Issue by arpita8** [alibaba/AICITY2024_Track2_AliOpenTrek_CityLLaVA#2]
I don't see nay results in results folder, as the file named ```inference.json``` is empty file. Do you plan to provide the results?
Thank you

**Comment by Youngluc** [comment]
The folder `results` and the file `inference_results.json` just serve as the placeholder in the repo. If you want the detailed inference results we have implemented, please provide your e-mail and we will send it to u.

**Comment by arpita8** [comment]
Can you please share your results on` arpita.vats09@gmail.com`. Thank you

**Comment by qingchunlizhi** [comment]
> Can you please share your results on` arpita.vats09@gmail.com`. Thank you

Sent, please check your email
