### ISSUE TITLE
generate_test_frames.py

### ISSUE THREAD

**Issue by mfaraki** [alibaba/AICITY2024_Track2_AliOpenTrek_CityLLaVA#3]

**Comment by mfaraki** [comment]
NA

**Comment by mfaraki** [comment]
Hi, Thanks for sharing. I encountered this error in the test frame generation script:

File "/AICITY2024_Track2_AliOpenTrek_CityLLaVA/data_preprocess/generate_test_frames.py",  in <module>
    for event in os.listdir(os.path.join(global_image_path, 'normal_trimmed')):

FileNotFoundError: [Errno 2] No such file or directory: '/WTS/test_part/WTS_DATASET_PUBLIC_TEST/bbox_global/test/public/normal_trimmed'

**Comment by Youngluc** [comment]
> Hi, Thanks for sharing. I encountered this error in the test frame generation script:
> 
> File "/AICITY2024_Track2_AliOpenTrek_CityLLaVA/data_preprocess/generate_test_frames.py", in for event in os.listdir(os.path.join(global_image_path, 'normal_trimmed')):
> 
> FileNotFoundError: [Errno 2] No such file or directory: '/WTS/test_part/WTS_DATASET_PUBLIC_TEST/bbox_global/test/public/normal_trimmed'

Hi, sry for late response. Maybe you can revised data path according to your file organization if error persistent. All normally in my env.
